### PR TITLE
Fix VILLASnode in Dockerfiles

### PR DESCRIPTION
**Pull request by pipeacosta**
This PR solves #291

### CODE REVIEW

**Comment by stv0g** [comment]
LGTM, but can you elaborate why you've choosen a VILLASnode version from February '24 while the last commit is just a week old?

**Comment by pipeacosta** [comment]
Hi @stv0g, There is no specific reason for having used that commit, we only need a stable version of VILLASnode. Do you have any recommendation in this regard?

**Comment by stv0g** [comment]
@pipeacosta I would usually say we should use the latest available commit which is not broken. But I think we can also go ahead with this one and update again in some time..

**Review by stv0g — APPROVED** [review]

**Review by leonardocarreras — DISMISSED** [review]
Looks good

Should we also do the same with the scripts? 

https://github.com/sogno-platform/dpsim/blob/f07066ab9941dfcb35e4acaf7086168f2b3462fb/packaging/Shell/install-ubuntu-deps.sh#L4

https://github.com/sogno-platform/dpsim/blob/f07066ab9941dfcb35e4acaf7086168f2b3462fb/packaging/Shell/install-fedora-deps.sh#L4

https://github.com/sogno-platform/dpsim/blob/f07066ab9941dfcb35e4acaf7086168f2b3462fb/packaging/Shell/install-fedora-deps-dev.sh#L4

**Comment by stv0g** [comment]
@pipeacosta Could you also adjust the commit refs in the locations mentioned by @leonardocarreras ?

**Comment by pipeacosta** [comment]
@stv0g done

**Review by stv0g — APPROVED** [review]

**Comment by stv0g** [comment]
@m-mirz I think this ready to be merged

**Pull request merged**
